version: '3.7'

services:

  api:
    container_name: node-2
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 5001:5001
    depends_on:
      - postgres
    networks:
      - api_network

  postgres:
    image: postgres:14.0-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: 5433
      POSTGRES_SERVICE: ${DB_HOST}
    restart: always
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - api_network

volumes:
  postgres_data:

networks:
    api_network:
        driver: bridge