"""add fee

Revision ID: 1a6abc2dfab2
Revises: a2c49b7f179e
Create Date: 2023-11-22 22:20:57.747438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a6abc2dfab2'
down_revision: Union[str, None] = 'a2c49b7f179e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('fee', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'fee')
    # ### end Alembic commands ###
